#    color0
#    color1
#    color2
#    color3
#    color4
#    color5
#    color6
#    color7
#    color8
#    color9
#    color10
#    color11
#    color12
#    color13
#    color14
#    color15
#    background
#    foreground
#    cursor
#    wallpaper

backend = "thumb"
color_space = "lch"

[templates.colors]
template = "colors"
target = "~/.config/zyxtarch/colors/colors"

[templates.colors-sh]
template = "colors.sh"
target = "~/.config/zyxtarch/colors/colors.sh"

[templates.vesktop]
template = "vesktop.css"
target = "~/.config/vesktop/settings/quickCss.css"

[templates.kitty]
template = "colors-kitty.conf"
target = "~/.config/kitty/kitty.conf"

[templates.colors-json]
template = "colors.json"
target = "~/.config/zyxtarch/colors/colors.json"

[templates.colors-css]
template = "colors.css"
target = "~/.config/zyxtarch/colors/colors.css"

[templates.colors-rasi]
template = "colors.rasi"
target = "~/.config/zyxtarch/colors/colors.rasi"

[templates.colors-scss]
template = "colors.scss"
target = "~/.config/zyxtarch/colors/colors.scss"

[templates.dunst]
template = "dunstrc"
target = "~/.config/zyxtarch/dunst/dunstrc"

[templates.eww-scss]
template = "colors-eww.scss"
target = "~/.config/zyxtarch/ewwii/ewwii.scss"

[templates.rmpc]
template = "colors-rmpc.ron"
target = "~/.config/zyxtarch/music/rmpc/theme.ron"
