[colors]
background = '#0d151f8e'
black = '#0d151f'
blue = '#445293'
cursor = '#c2c4c7'
cyan = '#4B5A9C'
foreground = '#c2c4c7'
green = '#54788F'
magenta = '#5D839B'
red = '#61869D'
tabs = '#c2c4c7'
tabs-active = '#678CA2'
white = '#c2c4c7'
yellow = '#c2c4c7'
dim-black = '#0d151f8e'
dim-blue = '#4452938e'
dim-cyan = '#4B5A9C8e'
dim-foreground = '#c2c4c78e'
dim-green = '#54788F8e'
dim-magenta = '#5D839B8e'
dim-red = '#61869D8e'
dim-white = '#678CA28e'
dim-yellow = '#c2c4c78e'
light-black = '#445293'
light-blue = '#4B5A9C'
light-cyan = '#54788F'
light-foreground = '#5D839B'
light-green = '#61869D'
light-magenta = '#678CA2'
light-red = '#c2c4c7'
light-white = '#445293'
light-yellow = '#4B5A9C'
